### ISSUE TITLE
Basic #1

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#1]
1

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x19a7764c9906d95b1142d12681eb8cd56bbe26a5a3627f549590b0b536ccdd9f](https://ropsten.etherscan.io/tx/0x19a7764c9906d95b1142d12681eb8cd56bbe26a5a3627f549590b0b536ccdd9f)
