### ISSUE TITLE
Test 3

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#10]
dfdfdfdf

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x560970aeb313a51906429aec0198a696b31ba710bde2b291d65a3b11453544a5](https://ropsten.etherscan.io/tx/0x560970aeb313a51906429aec0198a696b31ba710bde2b291d65a3b11453544a5)

**Comment by Chu127001** [comment]
just to menrtion #14
