### ISSUE TITLE
fresh_issue_for PR commit

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#103]
fresh_issue_for PR commit

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x37fe3e4ca687841b72631882d741ed25f6b5a33971b1f5f718e1fddbfcb098f7](https://ropsten.etherscan.io/tx/0x37fe3e4ca687841b72631882d741ed25f6b5a33971b1f5f718e1fddbfcb098f7)
