### ISSUE TITLE
Test 4

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#12]
test4

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x0e890668d55b5f66b40d83ef3fe267ffdaa863fbae05a6a36d87fa62f0cf04ba](https://ropsten.etherscan.io/tx/0x0e890668d55b5f66b40d83ef3fe267ffdaa863fbae05a6a36d87fa62f0cf04ba)
