### ISSUE TITLE
[Test]Show app-db changes which was made by selected event

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#14]
In current implementation if you click on event in the left panel list, you can see event vector in separate panel, it would be good also to see the app-db data which was changed by this event, for example, if we had app-db

{:a 1 :b 3}
and selected event changed :b key on 4 we should see

{:b 4}
so it should be a difference of app-db before this event and after

This task should be done for both re-frisk and re-frisk-remote #12

**Comment by Chu127001** [comment]
reference to #13

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x0269418e25a56fd4d18d911d0e8495d4828989fd478f45948dd7ab2826116882](https://ropsten.etherscan.io/tx/0x0269418e25a56fd4d18d911d0e8495d4828989fd478f45948dd7ab2826116882)
