### ISSUE TITLE
same address 3

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#148]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x9d25ef0b8569cab3cfa6838bc5cf2ef7506b2ea8f52fd281618a6702b1d6e443](https://ropsten.etherscan.io/tx/0x9d25ef0b8569cab3cfa6838bc5cf2ef7506b2ea8f52fd281618a6702b1d6e443)
