### ISSUE TITLE
same address 4

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#149]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x57e7fc0a1d238bdbad82b19522208791e1ea6d39b037a624e8a2e31b2d76af72](https://ropsten.etherscan.io/tx/0x57e7fc0a1d238bdbad82b19522208791e1ea6d39b037a624e8a2e31b2d76af72)
