### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#152]
new issue

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xb465fb439d639255aaa1c47a33420195446d607086ee4f1396c7a1596b36345f](https://ropsten.etherscan.io/tx/0xb465fb439d639255aaa1c47a33420195446d607086ee4f1396c7a1596b36345f)
