### ISSUE TITLE
issue_to_confirm_Payout

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#153]
issue_to_confirm_Payout

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x5a6d0f687761ae234b0e87ec1c77084b326504f29fca3a3b6dba3d4f5c083052](https://ropsten.etherscan.io/tx/0x5a6d0f687761ae234b0e87ec1c77084b326504f29fca3a3b6dba3d4f5c083052)
