### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#18]
dfsdf

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xc34fe9b70fdff34a7f6e9f7a4ae1c0459fbb394a0e424e44e6d2e4dc75c685c4](https://ropsten.etherscan.io/tx/0xc34fe9b70fdff34a7f6e9f7a4ae1c0459fbb394a0e424e44e6d2e4dc75c685c4)
