### ISSUE TITLE
Signing wait

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#20]
Signing wait

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xb9bef6db2091b2aa30855817c91f72298b9a976f8408918fb6329c7c6f6880a8](https://ropsten.etherscan.io/tx/0xb9bef6db2091b2aa30855817c91f72298b9a976f8408918fb6329c7c6f6880a8)
