### ISSUE TITLE
Sign wait 

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#22]
2

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xf16115269aa84c17358e92f5a1d9bf545a9e8cb8f933812387c6ff6669cee507](https://ropsten.etherscan.io/tx/0xf16115269aa84c17358e92f5a1d9bf545a9e8cb8f933812387c6ff6669cee507)
