### ISSUE TITLE
Issue to close

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#27]
Issue to close

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x1d24a94d1783e1c42dc81f372babcac8b4d3fde16b4cbaa2a5d2623b61c5bfa7](https://ropsten.etherscan.io/tx/0x1d24a94d1783e1c42dc81f372babcac8b4d3fde16b4cbaa2a5d2623b61c5bfa7)
