### ISSUE TITLE
regress 5

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#29]
5

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xc74ee05aaea88d05cc036a2e46522d5073adb94ec2b58e2b1ffd58a0f06fa981](https://ropsten.etherscan.io/tx/0xc74ee05aaea88d05cc036a2e46522d5073adb94ec2b58e2b1ffd58a0f06fa981)
