### ISSUE TITLE
B2 issue

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#32]
other comment

**Comment by churik** [comment]
Some toother comment

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x2cfe5a4ec5f546e0de6e51cada95195d57c4bb8db33c1b1764b8bfe2892b8971](https://ropsten.etherscan.io/tx/0x2cfe5a4ec5f546e0de6e51cada95195d57c4bb8db33c1b1764b8bfe2892b8971)
