### ISSUE TITLE
B_3 new

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#35]
kkkkk

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x247ff709c9ea4bce4ea8f5d1751da521e3853dfbf0dcadb79d4ba687cf9c4f46](https://ropsten.etherscan.io/tx/0x247ff709c9ea4bce4ea8f5d1751da521e3853dfbf0dcadb79d4ba687cf9c4f46)
