### ISSUE TITLE
Ava check

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#38]
123

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x398fe22bb7c1842f0683dc6922a4730568948ae0c2fcf1b7ccb87b669f31869d](https://ropsten.etherscan.io/tx/0x398fe22bb7c1842f0683dc6922a4730568948ae0c2fcf1b7ccb87b669f31869d)
