### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#41]
Rebase

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x9814f0eb774c0a7da9f2b82794ba25a85aad95d9545905fc1b6a508301e1b788](https://ropsten.etherscan.io/tx/0x9814f0eb774c0a7da9f2b82794ba25a85aad95d9545905fc1b6a508301e1b788)
