### ISSUE TITLE
SMOKEcheck B1

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#46]
[comment]: SMOKEcheck B1

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xca605943b5ba3836bb894435896656331327d8e27742bbdac5f1284b3ea5e1d7](https://ropsten.etherscan.io/tx/0xca605943b5ba3836bb894435896656331327d8e27742bbdac5f1284b3ea5e1d7)
