### ISSUE TITLE
SMOKE check B1

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#47]
[comment]: SMOKE check B1

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x36d92997517a866bb9b1c84ce21ff8a9a3ae31fbf39b0cc3d99733b70a8049a0](https://ropsten.etherscan.io/tx/0x36d92997517a866bb9b1c84ce21ff8a9a3ae31fbf39b0cc3d99733b70a8049a0)
