### ISSUE TITLE
SMOKEcheck B2

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#49]
smokeCheckB2 dddd

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x87d0df012732763a7bc9e72512f79c9697de42f2cf607dfc5fdfaddcf158cbc6](https://ropsten.etherscan.io/tx/0x87d0df012732763a7bc9e72512f79c9697de42f2cf607dfc5fdfaddcf158cbc6)

**Comment by Chu127001** [comment]
mention #50
