### ISSUE TITLE
Bounty remove check (2)

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#5]
comm

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xc063a982dc05513b520ab2db6e9dc529a85f6cbdc861c62adc38e0947b15e6d5](https://ropsten.etherscan.io/tx/0xc063a982dc05513b520ab2db6e9dc529a85f6cbdc861c62adc38e0947b15e6d5)
