### ISSUE TITLE
Smoke check B3 15.12

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#50]
fhfhffhhh

**Comment by Chu127001** [comment]
fixes #47

**Comment by Chu127001** [comment]
reference #48

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x6aea4f1645191da3152ade984928a4a02da37cc1ca35f5f178691c1871b1d632](https://ropsten.etherscan.io/tx/0x6aea4f1645191da3152ade984928a4a02da37cc1ca35f5f178691c1871b1d632)
