### ISSUE TITLE
issue like 2755

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#57]
issue like 2755

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x785489a494d8515e9fc58e5f8f2a4658b5037e415bec6e7ef2f89a52dcebf749](https://ropsten.etherscan.io/tx/0x785489a494d8515e9fc58e5f8f2a4658b5037e415bec6e7ef2f89a52dcebf749)
