### ISSUE TITLE
Issue 8

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#60]
12345

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x295d33a56b3fecd5e657036993b97756f7463ef95707d27380056846390f694c](https://ropsten.etherscan.io/tx/0x295d33a56b3fecd5e657036993b97756f7463ef95707d27380056846390f694c)

**Comment by Chu127001** [comment]
hghghghhggg
