### ISSUE TITLE
New issue Chu

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#61]
new issue

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xdaf095266bcc7d654b052d8f1744a7558cbe736e4ea19df662947bae809b13f5](https://ropsten.etherscan.io/tx/0xdaf095266bcc7d654b052d8f1744a7558cbe736e4ea19df662947bae809b13f5)
