### ISSUE TITLE
Autobot test1

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#62]
sdfsdfsfd

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xc965c41689b07bc2dc7047a454963e203a94e937570b247c713f7175288c8087](https://ropsten.etherscan.io/tx/0xc965c41689b07bc2dc7047a454963e203a94e937570b247c713f7175288c8087)
