### ISSUE TITLE
Very long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long nameVery long name

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#64]
Very long name

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x6809a8b8a0c24641f1d4014f0d29d105932ead27c7a8adacd2a67b72b313e14c](https://ropsten.etherscan.io/tx/0x6809a8b8a0c24641f1d4014f0d29d105932ead27c7a8adacd2a67b72b313e14c)
