### ISSUE TITLE
NewTestIssue

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#71]
NewTestIssue

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x8cba644435376b4d11e0437d7b2850678024854d86cb9ade71d070f7ecd0517e](https://ropsten.etherscan.io/tx/0x8cba644435376b4d11e0437d7b2850678024854d86cb9ade71d070f7ecd0517e)
