### ISSUE TITLE
NewTesting issue_downtime

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#74]
qqqqqq

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x34b50254a1703ce188cc9a6f2f9d40c61cbad1eb4778a28d52466ec0445be0bd](https://ropsten.etherscan.io/tx/0x34b50254a1703ce188cc9a6f2f9d40c61cbad1eb4778a28d52466ec0445be0bd)
