### ISSUE TITLE
1 issue

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#75]
sdfsdfdsf

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x7805553c739504b2546e3e9be71a0638078a837b264770c3382340de804d1231](https://ropsten.etherscan.io/tx/0x7805553c739504b2546e3e9be71a0638078a837b264770c3382340de804d1231)
