### ISSUE TITLE
Issue_to_check_address

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#76]
fffff

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x07b44b9fc95218523e49da3136c0b53c60ceac98c2f1c6593f6db435d0d5c65e](https://ropsten.etherscan.io/tx/0x07b44b9fc95218523e49da3136c0b53c60ceac98c2f1c6593f6db435d0d5c65e)
