### ISSUE TITLE
Additional_issue_tocheck_address

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#77]
Additional_issue_tocheck_address

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xf5d398e09f505cee376be6a09aa23b72354bb9d7397b0d3711fb331a1fa8ff06](https://ropsten.etherscan.io/tx/0xf5d398e09f505cee376be6a09aa23b72354bb9d7397b0d3711fb331a1fa8ff06)
