### ISSUE TITLE
Issue_testing_env

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#83]
ddddddd

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x0d8379edef468dd3b9cba6508edf25f7ad794971336438b71337fd4b296e7146](https://ropsten.etherscan.io/tx/0x0d8379edef468dd3b9cba6508edf25f7ad794971336438b71337fd4b296e7146)
