### ISSUE TITLE
Issue to test staging

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#86]
Issue to test staging

**Comment by status-open-bounty** [comment]
![Contract deploying](https://testing.openbounty.status.im/img/deploying_contract.png)
Transaction: [0x8e4792b991b59426002d02d7ff5fc928cae2d2e67f5e9b85e8d16ef2079b498f](https://ropsten.etherscan.io/tx/0x8e4792b991b59426002d02d7ff5fc928cae2d2e67f5e9b85e8d16ef2079b498f)
