### ISSUE TITLE
Issue_to_test_st

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#87]
Issue_to_test_st

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x907c6a128e186c26c04fd64c6452de04c507a3e43d1271eac9816a3ab4b52d80](https://ropsten.etherscan.io/tx/0x907c6a128e186c26c04fd64c6452de04c507a3e43d1271eac9816a3ab4b52d80)
