### ISSUE TITLE
New_issue_staging

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#88]
New_issue_staging

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xb15952505f708bcb8b2ec1bd0b8dc4652cbeceb6df417c5f291661f7e07ee4f4](https://ropsten.etherscan.io/tx/0xb15952505f708bcb8b2ec1bd0b8dc4652cbeceb6df417c5f291661f7e07ee4f4)
