### ISSUE TITLE
Last_message_staging

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#89]
Last_message_staging

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xbc45e5c4bc2cdc2c87f0d563d4ce1c524aa394641be1171faad4d5f5e7793237](https://ropsten.etherscan.io/tx/0xbc45e5c4bc2cdc2c87f0d563d4ce1c524aa394641be1171faad4d5f5e7793237)
