### ISSUE TITLE
Test_test_to_check_one_issue

### ISSUE THREAD

**Issue by Chu127001** [NewOrGanizationSOB/RepoSOB#96]
Test_test_to_check_one_issue

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 20.00
Contract address: [0xc469b490893e04fb13ca631136556303cb4bb77b](https://ropsten.etherscan.io/address/0xc469b490893e04fb13ca631136556303cb4bb77b)
Network: Testnet (Ropsten)
Paid to: churik
Visit [https://openbounty.status.im:444](https://openbounty.status.im:444) to learn more.
